### ISSUE TITLE
Issues building in Visual Studio 2022

### ISSUE THREAD

**Issue by entropiccode** [andersblomqvist/bitfish-3.3.5#2]
I've cloned the repo and opened it in Visual Studio 2022.  I manually added the blackMagic.dll and fasmdll_managed.dll as references as stated in the instructions, and restored the other packages via NuGet.  However, when I go to build the solution, it tells me a large number of components still could not be found.  Additionally, the System.Text.Json.6.0.1 package seems to have a unique file path, as I have the System.Text.Json.6.0.1 package installed.

If you could provide a built executable as a release, or provide some guidance on what components I need to be updating that would be greatly appreciated.

**Comment by andersblomqvist** [comment]
Hi, sorry for the late answer.

I saw that the project was not setup well and had some static linking to other packages. I've fixed that so please try importing it again.

When I import the project by cloning the repo I do the following:

1. Clone the repo
2. Open `.sln` file with visual studio (I now use 22 edition)
3. Right-click the Bitfish project inside "Solution Explorer"
4. Click Manage NuGet Packages...
5. A warning at the top should show a message where you can click a restore button to the right. That will resolve the missing packages.
6. Build the project

**Comment by entropiccode** [comment]
Worked like a charm, thank you!
